import {MainPage} from "./Main";
import {AboutPage} from "./About";
import {AdvertisePage} from "./Advertise";
import {AllAdsPage} from "./AllAds";
import {CategoriesPage} from "./Categories";
import {AuthPage} from "./Auth";
import {ProfilePage} from "./Profile";
import {DetailPage} from "./Detail";
import {AdminPanel} from "./AdminPanel";
import {UserPage} from "./UserPage";
export {MainPage, AdminPanel, AboutPage, AdvertisePage, AllAdsPage, CategoriesPage, AuthPage, ProfilePage, DetailPage, UserPage};