import { MainPage } from "./Main";
import { AboutPage } from "./About";
import { AdvertisePage } from "./Advertise";
import { CategoriesPage } from "./Categories";
import { AuthPage } from "./Auth";
import { ProfilePage } from "./Profile";
import { DetailPage } from "./Detail";
import { AdminPanel } from "./AdminPanel";
import { UserPage } from "./User";
import { FavoritePage } from "./Favorite";
export { MainPage, AdminPanel, AboutPage, AdvertisePage, CategoriesPage, AuthPage, ProfilePage, DetailPage, UserPage, FavoritePage };